Use correct cms service
mirumee/nimara-ecommerce pull request #101
Opened 2024-12-04 15:48 UTC by soniaklimas

I want to merge this change because allows to switching cms service through Vercel env.

# Pull Request Checklist

- [ ] Test the changes locally to ensure they work as expected.
- [ ] Document the testing process and results in the pull request description. (Screen recording, screenshot etc)
- [ ] Include new tests for any new functionality or significant changes.
- [ ] Ensure that tests cover edge cases and potential failure points.
- [ ] Document the impact of the changes on the system, including potential risks and benefits.
- [ ] Provide a rollback plan in case the changes introduce critical issues.
- [ ] Update documentation to reflect any changes in functionality.

2024-12-04 16:49 UTC, karolkarolka requested changes

2024-12-04 16:49 UTC, karolkarolka commented on apps/storefront/src/services/cms.ts
> +  getCMSMenuService();
should work and no awaiting would be needed when importing the services in other files
```suggestion
export const cmsPageService: CMSPageService = await getCMSPageService();
export const cmsMenuService: CMSMenuService = await getCMSMenuService();
```

2024-12-04 21:42 UTC, karolkarolka approved these changes
Check before merging if setting CMS_SERVICE env on Vercel works on for your Preview build

2024-12-05 08:15 UTC, soniaklimas commented
I tested it and it works correctly - if you change CMS_SERVICE env on Vercel and do redeploy chosen CMS is used.

2024-12-05 08:15 UTC, merged