refactor: Copy and refactor nav
mirumee/nimara-ecommerce pull request #107
Opened 2024-12-08 21:33 UTC by soniaklimas

I want to merge this change because it copies nav from fashion branch and refactores it.

# Pull Request Checklist

- [ ] Test the changes locally to ensure they work as expected.
- [ ] Document the testing process and results in the pull request description. (Screen recording, screenshot etc)
- [ ] Include new tests for any new functionality or significant changes.
- [ ] Ensure that tests cover edge cases and potential failure points.
- [ ] Document the impact of the changes on the system, including potential risks and benefits.
- [ ] Provide a rollback plan in case the changes introduce critical issues.
- [ ] Update documentation to reflect any changes in functionality.

2024-12-10 10:52 UTC, karolkarolka requested changes

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/lib/helpers.ts
> -interface Paths {
what has happend to the deleted lines in this file? Aren't they or weren't used in Nimara anymore?

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/components/mobile-navigation.tsx
> +          <Link href={item.url} onClick={() => handleMenuItemClick()}>
```suggestion
          <Link href={item.url} onClick={() => onMenuItemClick(true)}>
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/components/mobile-navigation.tsx
> +                  <Link href={child.url} onClick={() => handleMenuItemClick()}>
```suggestion
                  <Link href={child.url} onClick={() =>onMenuItemClick(true)}>
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                    {item.children?.length
```suggestion
                    {!!item.children?.length &&
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/components/mobile-navigation.tsx
> +          {item.children?.length ? (
```suggestion
          {!!item.children?.length && (
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +              href={item.url || "#"}
```suggestion
              href={item.url}
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                    {item.children?.length
```suggestion
                    {!!item.children?.length &&
```

2024-12-10 10:52 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                              }}
```suggestion
                              onClick={() => setCurrentMenuItem("")}
```
why the onClick event should set the component's state as `menu item = empty string`?

2024-12-10 10:52 UTC, karolkarolka commented on packages/infrastructure/src/lib/serializers/cms-menu.ts
> +      "#",
why #?

2024-12-10 10:52 UTC, karolkarolka commented on packages/infrastructure/src/public/butter-cms/cms-menu/infrastructure/cms-menu-get-infra.ts
> +
```suggestion
```

2024-12-10 11:06 UTC, soniaklimas commented on apps/storefront/src/lib/helpers.ts
> -interface Paths {
All deleted functions are not used anymore in Nimara. Refactor of navigation simplified creating urls and most of that functions were related to that.

2024-12-10 11:24 UTC, soniaklimas commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                              }}
It manually closes menu - if you click on given menu item menu should not be visible. It is workaround to achieve that.

2024-12-10 15:44 UTC, karolkarolka commented on packages/infrastructure/src/lib/serializers/cms-menu.ts
> +      "#",
Yeah but all of the elements in the menu should be links so if someone won't set links via CMS the storefront should be notified so either make URLs as required fields in types or make a condition `item.url && <Link`. Setting the hash as the link value when it wasn't set in CMS doesn't seem right to me. The empty hash will navigate to the top of the page and be weirdly visible in URL

2024-12-10 15:50 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                            // onClick={() => setCurrentMenuItem("")}
to remove?

2024-12-10 15:50 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                                backgroundImage: `url(${child?.collectionImageUrl})`,
Can you check if the URLs uploaded to the CMS are handled by their CDNs and are returned as optimized images? The problem with setting the image as a background of the five is that the images won't be optimized and might cause the slow render issues

2024-12-11 10:32 UTC, soniaklimas commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                                backgroundImage: `url(${child?.collectionImageUrl})`,
Images (from Butter CMS and Saleor as well) are served in WebP format. They are also delivered via a CDN (CloudFront) with caching enabled. Is that enough?

2024-12-11 10:36 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/navigation.tsx
> +                                backgroundImage: `url(${child?.collectionImageUrl})`,
Yes. If the images will be served in WebP or AVIF instead of raw/large PNGs, JPEGs, there would be no need to switch from background image to next/image

2024-12-11 10:40 UTC, karolkarolka approved these changes

2024-12-11 10:42 UTC, merged