feat: Improve seo
mirumee/nimara-ecommerce pull request #57
Opened 2024-10-24 14:33 UTC by soniaklimas

I want to merge this change because it adds sitemap.xml, adjust robots.ts and ads <h1> where required.

# Pull Request Checklist

- [ ] Test the changes locally to ensure they work as expected.
- [ ] Document the testing process and results in the pull request description. (Screen recording, screenshot etc)
- [ ] Include new tests for any new functionality or significant changes.
- [ ] Ensure that tests cover edge cases and potential failure points.
- [ ] Document the impact of the changes on the system, including potential risks and benefits.
- [ ] Provide a rollback plan in case the changes introduce critical issues.
- [ ] Update documentation to reflect any changes in functionality.

2024-10-24 16:31 UTC, karolkarolka requested changes

2024-10-24 16:31 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/_components/hero-banner.tsx
> +        <h1 className="pb-8 text-3xl font-medium lg:text-5xl">
won't it conflict with logo img (h1) in header?

2024-10-24 16:31 UTC, karolkarolka commented on apps/storefront/src/app/[locale]/(main)/search/page.tsx
> +          <h1 className="text-2xl">{getHeader()}</h1>
```suggestion
          getHeader() && <h1 className="text-2xl">{getHeader()}</h1>
```

+ same question as above with h1

2024-10-24 16:31 UTC, karolkarolka commented on apps/storefront/src/app/robots.ts
> +    sitemap: `${publicUrl}/sitemap.xml`,
```suggestion
    sitemap: `${process.env.BASE_URL}/sitemap.xml`,
```

2024-10-24 16:31 UTC, karolkarolka commented on apps/storefront/src/app/sitemap.ts
> +import { type MetadataRoute } from "next";
```suggestion
import type { MetadataRoute } from "next";
```

2024-10-24 16:31 UTC, karolkarolka commented on apps/storefront/src/app/sitemap.ts
> +    currency: "USD",
what about other currency and locale?

2024-10-25 07:51 UTC, soniaklimas commented on apps/storefront/src/app/[locale]/(main)/_components/hero-banner.tsx
> +        <h1 className="pb-8 text-3xl font-medium lg:text-5xl">
It was suggestion from SEO person's feedback. I checked lighthouse report and it does not say there is any conflict.

2024-10-25 07:51 UTC, soniaklimas commented on apps/storefront/src/app/[locale]/(main)/search/page.tsx
> +          <h1 className="text-2xl">{getHeader()}</h1>
There is no conflict in lighthouse report. But it does not seem right - I changed h1 in navigation to h2.

2024-10-25 07:53 UTC, soniaklimas commented on apps/storefront/src/app/sitemap.ts
> +    currency: "USD",
I used those currency, channel and language only to fetch products' slugs. There are generated urls in sitemap.xml file which work without locales (there is automatic redirection).

2024-10-25 08:48 UTC, karolkarolka commented on apps/storefront/src/app/sitemap.ts
> +    currency: "USD",
The sitemap should show all links with their alternate links in other locale but this will be done in other task

2024-10-25 09:17 UTC, karolkarolka approved these changes

2024-10-25 09:18 UTC, merged